shared:
  images:
    image1:
      imageTag: "1.0"
      imageDigest: "sha256:d115f8aad9c4ae7ee21ae75bbcb3dc2c5dbf1.07bf6dad6dcb5aac5c02003bde"
    image2:
      imageTag: "1.0.0"
      imageDigest: "sha256:old123"
spec:
  template:
    metadata:
      annotations:
        sidecar:
          container:
            details:
              imageTag: "1.0"
              imageDigest: "sha256:"
    spec:
      mainContainer:
        image:
          config:
            imageTag: "1.0"
            imageDigest: "sha256:sdsfsdfs."
        other: "value"
      initContainer:
        container:
          status:
            imageTag: "1.0"
            imageDigest: "sha256:sds."
