name: Image Update Request
description: Image Update Request.
labels: ["image-update"] # Optional label for filtering issues
title: "[Image Update]"
body:
  - type: textarea
    id: image_names
    attributes:
      label: Image along with tags
      description: Enter the image names along with tags separated by new line.
      placeholder: |
        lj:11.0.1.1
        is:11.0.1.4
