name: Image Update Request
description: Image Update Request.
labels: ["image-update-request"] # Optional label for filtering issues
body:
  - type: input
    id: image_names
    attributes:
      label: Image Names
      description: Enter the image names separated by comma.
      placeholder: is,lj,um,engine
  - type: input
    id: image_tags
    attributes:
      label: Image Tags
      description: Enter the image tags separated by comma.
      placeholder: 11.0.1.1,11.0.1.4
