name: Product Workflow Request
description: Request a workflow run for a specific product and timeframe.
labels: ["workflow-request"] # Optional label for filtering issues
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details for your product workflow request.
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Select the product(s) for this workflow.
      multiple: true
      options:
        - int
        - e2em
        - b2b
        # Add your actual product options here
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the environment for this workflow.
      options:
        - aws-dev
        - az-dev
        - aws-stage
        - az-stage
        # Add your actual environment options here
  - type: input
    id: start_datetime
    attributes:
      label: Start Date & Time (YYYY-MM-DD HH:mm)
      description: Enter the desired start date and time in YYYY-MM-DD HH:mm format (e.g., 2023-12-25 09:00).
      placeholder: YYYY-MM-DD HH:mm
  - type: input
    id: end_datetime
    attributes:
      label: End Date & Time (YYYY-MM-DD HH:mm)
      description: Enter the desired end date and time in YYYY-MM-DD HH:mm format (e.g., 2023-12-26 17:00).
      placeholder: YYYY-MM-DD HH:mm
